config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items

  root 'items#index'
  
  get "items/new", to: 'items#new'

  get "items/edit", to: 'items#edit'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
        @item = Item.all
        render  :index
    end

    def new
        @item = Item.new        
        render :new
    end

    def create
        @item = Item.new(items_params)
        if(@item.save)
            redirect_to "/"
        end
    end

    def items_params
        params.require(:item).permit(:serial_number, :description, :supplier, :status, :lender)
    end

    def edit
        @item = Item.find(params[:id].to_i)
        render :edit
    end

    def show
        @item = Item.find(params[:id].to_i)
    end

    def update
        @item = Item.find(params[:id].to_i)
        @item.update(items_params)
    end

    def destroy
        @item = Item.find(params[:id].to_i)
        @item.destroy
        redirect_to(items_path)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%=form_for(@item) do |f| %>
    <p>
    <%=f.label 'Serial Number', :class => "textForm"  %><br>
    <%=f.text_field :serial_number, :class => "form" %>
    </p>
    <p>
    <%=f.label 'Description', :class => "textForm"  %><br>
    <%=f.text_field :description, :class => "form" %>
    </p>
    <p>
    <%=f.label 'Suplier', :class => "textForm"  %><br>
    <%=f.text_field :supplier, :class => "form" %>
    </p>
    <p>
    <%=f.label 'Status', :class => "textForm"  %><br>
    <%=f.text_field :status, :class => "form" %>
    </p>
    <p>
    <%=f.label 'Lender', :class => "textForm"  %><br>
    <%=f.text_field :lender, :class => "form" %>
    </p>
    <%=f.submit 'Add', :class => "btn" %>
<%end%>

app/views/items/edit.html.erb
<h1>Edit Page For <%= @item.description %> with SERIAL NUMBER : <%= @item.serial_number %> </h1>

<%= render 'form', item: @item %>
<%= link_to 'Show', @item, :class => "btn_over"  %>
<%= link_to 'Back', items_path , :class => "btn_over" %>

app/views/items/index.html.erb
<h1>Items Inventory </h1>

<%= link_to 'Add Item to the Inventory', items_new_path, :class => "btn" %>

<h2> Did you find all the items you need? If not add the item you want by clicking the Add item button</h2>

<table>   
    <thead>
        <th>Serial Number</th>
        <th>Description</th>
        <th>Supplier</th>
        <th>Status</th>
        <th>Lender</th>
    </thead>

    <tbody>
        <% @item.each do |item| %>
            <tr>
                <td style="padding:20px"><%= item.serial_number%></td>
                <td><%= item.description %></td>
                <td><%= item.supplier %></td>
                <td style="color: green;"><%= item.status %></td>
                <td><%= item.lender %></td>
                <td><%= link_to 'Show', item, :class => "btn" %></td>
                <td><%= link_to 'Edit', edit_item_path(item), :class => "btn" %></td> 
                <td><%= link_to 'Destroy', item, method: :delete, data: {confirm: 'Are you sure?'} , :class => "btn"  %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/items/new.html.erb
<h1>Input a new Item in to the Inventory</h1>


<%= render 'form', item: @item %>
<%= link_to 'Back', items_path, :class => "btn_over" %>

app/views/items/show.html.erb
<h1>Here is your selected Item: <%= @item.description  %></h1>


<p>
    Name:
    <%= @item.serial_number %>
</p>

<p>
    Description:
    <%= @item.description %>
</p>

<p>
    Supplier:
    <%= @item.supplier %>
</p>

<p>
    Status:
    <%= @item.status %>
</p>

<p>
    Lender:
    <%= @item.lender %>
</p>



<%=link_to 'Back', items_path, :class => "btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ItemInventory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>